pip3 install django
pip3 install django-bootstrap4
pip3 install social-auth-app-django
pip3 install pillow
pip3 install easy-thumbnails
pip3 install django-cleanup
pip3 install django-simple-captcha
pip3 install djangorestframework
pip3 install django-cors-headers
